services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  app:  
    build: 
      context: .
      dockerfile: DockerFile
    ports:
      - '8888:8888'
    depends_on:
      - postgres
